app <- ShinyDriver$new("../../")
app$snapshotInit("resets")

app$setInputs(targetType = "Archive")
app$setInputs(puzzleDate = "2022-02-22")
app$setInputs(typedC = "click")
app$setInputs(typedR = "click")
app$setInputs(typedA = "click")
app$setInputs(typedT = "click")
app$setInputs(typedE = "click")
app$setInputs(typedENTER = "click")
app$setInputs(typedW = "click")
app$setInputs(typedH = "click")
app$setInputs(typedI = "click")
app$setInputs(typedN = "click")
app$setInputs(typedE = "click")
app$setInputs(typedENTER = "click")
app$setInputs(typedE = "click")
app$setInputs(typedV = "click")
app$setInputs(typedO = "click")
app$setInputs(typedK = "click")
app$setInputs(typedE = "click")
app$setInputs(typedENTER = "click")
app$snapshot()
app$setInputs(targetType = "User")
app$setInputs(Sought = "thorn")
app$snapshot()
app$setInputs(typedB = "click")
app$setInputs(typedR = "click")
app$setInputs(typedO = "click")
app$setInputs(typedK = "click")
app$setInputs(typedE = "click")
app$setInputs(typedENTER = "click")
app$setInputs(typedS = "click")
app$setInputs(typedH = "click")
app$setInputs(typedO = "click")
app$setInputs(typedR = "click")
app$setInputs(typedN = "click")
app$setInputs(typedENTER = "click")
app$snapshot()
app$setInputs(targetType = "Random")
app$setInputs(randomPuzzle = "click")
app$snapshot()
