app <- ShinyDriver$new("../../")
app$snapshotInit("twoWords")

app$setInputs(puzzleDate = "2022-02-07")
app$setInputs(Sought = "PANIC")
app$setInputs(typedP = "click")
app$setInputs(typedA = "click")
app$setInputs(typedS = "click")
app$setInputs(typedT = "click")
app$setInputs(typedA = "click")
app$snapshot()
app$setInputs(typedENTER = "click")
app$snapshot()
app$setInputs(typedP = "click")
app$setInputs(typedA = "click")
app$setInputs(typedI = "click")
app$setInputs(typedN = "click")
app$setInputs(typedS = "click")
app$snapshot()
app$setInputs(typedENTER = "click")
app$snapshot()
