app <- ShinyDriver$new("../../")
app$snapshotInit("UIRunthrough")

app$setInputs(puzzleDate = "2022-02-07")
app$snapshot()
app$setInputs(targetType = "Archive")
app$setInputs(puzzleDate = "2022-02-06")
app$setInputs(typedE = "click")
app$setInputs(typedL = "click")
app$setInputs(typedV = "click")
app$setInputs(typedA = "click")
app$setInputs(typedR = "click")
app$setInputs(typedENTER = "click")
app$snapshot()
app$setInputs(typedDELETE = "click")
app$setInputs(typedDELETE = "click")
app$setInputs(typedDELETE = "click")
app$snapshot()
app$setInputs(typedD = "click")
app$setInputs(typedE = "click")
app$setInputs(typedR = "click")
app$snapshot()
app$setInputs(typedENTER = "click")
app$setInputs(typedP = "click")
app$setInputs(typedL = "click")
app$setInputs(typedE = "click")
app$setInputs(typedA = "click")
app$setInputs(typedT = "click")
app$setInputs(typedENTER = "click")
app$snapshot()
app$setInputs(targetType = "User")
app$setInputs(Sought = "snack")
app$setInputs(typedS = "click")
app$setInputs(typedT = "click")
app$setInputs(typedA = "click")
app$setInputs(typedC = "click")
app$setInputs(typedK = "click")
app$setInputs(typedENTER = "click")
app$setInputs(targetType = "Random")
app$setInputs(randomPuzzle = "click")
app$snapshot()
